# 1.1 Activity

For our Unit 1 activities, we will be working with data from the Cornell Lab of Ornithology "eBird" regarding sightings of specific bird species.

In this unit, our focus will be using Pandas to manipulate or "wrangle" data to initiate Exploratory Data Analysis (EDA) for statistical inference. The demonstration video has a basic overview of how to do this. Try this independently to build on some of the skills introduced thus far.  

By the end of this assignment, you will:

1. Mount your Google Drive to Colab 
2. Import a CSV file into a Pandas DataFrame
3. Convert a Pandas DataFrame into a CSV file
4. Download the CSV file to your local machine
5. Reflect on this first experience using Colab


Follow the subsequent steps to import the `birds.csv` file into your Google Colaboratory environment as a Pandas DataFrame, explore the data, and export your new dataset.

Although this activity includes instructions, you must appropriately comment your code. Failure to do so will result in point deductions.

Suppose you get stuck at any point in the activity. Post your code to the discussion forum in Canvas. We can debug code in the forum, which will help you and your classmates learn more coding skills!

**Note:** You must post more than 24 hours before the assignment deadline to ensure a response.

## Task 1: Setup Workspace

Using the `Code snippets` tool in the lower left hand corner of the Colab interface (<> icon), mount your Google Drive to the Colab environment. Refer back to the Practice Colab Assignment if you get stuck.

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

Import the gdown library to download 

---

files from the shared Google Drive for the class.

In [ ]:
import gdown

Import the Pandas library as pd ([Reference](https://pandas.pydata.org/docs/user_guide/dsintro.html)).

In [ ]:
import pandas as pd

Import the NumPy library as np ([Reference](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-import-numpy)).

In [ ]:
import numpy as np

## Task 2: Loading Data

Use the gdown library to download the dataset for this assignment.

```
!gdown 1JnVoGknl02xI-zBfCK9czx6E-OeC3Z9e
```

OR

```
gdown.download(id = '1JnVoGknl02xI-zBfCK9czx6E-OeC3Z9e')
```

In [ ]:
gdown.download(id = '1JnVoGknl02xI-zBfCK9czx6E-OeC3Z9e')

Downloading...
From: https://drive.google.com/uc?id=1JnVoGknl02xI-zBfCK9czx6E-OeC3Z9e
To: /content/birds.csv
100%|██████████| 163k/163k [00:00<00:00, 67.5MB/s]

'birds.csv'

Assign the downloaded data to a new DataFrame variable named "Birds" using the Pandas [read_csv()](https://pandas.pydata.org/docs/user_guide/io.html#csv-text-files) method.

In [ ]:
Birds = pd.read_csv('/content/birds.csv')

Return the first few lines of data using the [head()](https://pandas.pydata.org/docs/user_guide/basics.html#head-and-tail) method to see what we're working with.

In [ ]:
Birds.head()

,Taxonomic Order,Category,Common Name,Scientific Name,Subspecies,Subspecies.1,Observation Count,Locality Type,Latitude,Longitude,Observation Date,Observation Time,Protocol Type,Duration Minutes,Effort Distance KM,Number Observers,All Species Reported
0,20762,species,American Crow,Corvus brachyrhynchos,NaN,NaN,1,P,32.176196,-86.352121,4/29/22,16:05:00,Traveling,84.0,1.305,1,1
1,20762,species,American Crow,Corvus brachyrhynchos,NaN,NaN,1,H,32.358285,-86.454432,4/26/22,17:00:00,Traveling,60.0,1.609,2,1
2,20762,species,American Crow,Corvus brachyrhynchos,NaN,NaN,2,P,32.310409,-86.101011,4/23/22,17:19:00,Traveling,6.0,9.740,4,1
3,20762,species,American Crow,Corvus brachyrhynchos,NaN,NaN,3,P,32.105727,-86.024669,4/28/22,6:17:00,Traveling,35.0,0.306,1,1
4,20762,species,American Crow,Corvus brachyrhynchos,NaN,NaN,1,P,32.345618,-86.032910,4/17/22,12:29:00,Stationary,61.0,NaN,1,1

## Task 3: Exporting Data

Now that you have your data loaded into Colab you would normally be manipulating it. For now, let's see if we can export our data.
 
Convert the DataFrame back to a csv file called "NewBirds.csv" using the Pandas [to_csv()](https://pandas.pydata.org/docs/user_guide/io.html#io-store-in-csv) method.

In [ ]:
Birds.to_csv('NewBirds.csv')

Download "NewBirds.csv" to your local machine using the files package from google.colab ([Reference](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=hauvGV4hV-Mh)).

In [ ]:
from google.colab import files
files.download('NewBirds.csv')

## Task 4: Thought Question

> *Comparing Google Colab to any other statistical package you have used, what is one advantage to Colab? What is one disadvantage?*

I think a huge advantage within Colab is the code snippts section. Having a readily available library of sample code you can edit and apply to your purposes is fantastic.
One disadvantage is that it is a different environment to a local python coding terminal. Some of the features I'm suer I will get used to in Colab won't be available if I used Python in a different format.